export const githubIds = [
  { name: "Dilli", id: "dilliswararaogalala-lgtm" },
  { name: "Sandip Saha", id: "sandipsaha2005" },
  { name: "Santo", id: "Santo-Undefined" },
  { name: "Gurram Chiranjeevi", id: "GurramChiranjeevi" },
  { name: "Abhay Pratap Singh", id: "AbhayPratapSingh1" },
  { name: "Sivaji Sai", id: "SIVAJISAI" },
  { name: "Athul S M", id: "athul-s-m" },
  { name: "Pradip Chjana", id: "pradipchjana" },
  { name: "Gorre Jyothi Praveen", id: "gorrejyothipraveen" },
  { name: "Samiran", id: "samirangharami" },
  { name: "Jayanth", id: "jayanth-14" },
  { name: "Rahul Vishwakarma", id: "rahulVishwakarma03" },
  { name: "Sidhartha", id: "ItsSidhartha" },
  { name: "Ibrahim", id: "ibrahim-thoughtworks" },
  { name: "Rashmika Gandra", id: "RashmikaGandra" },
  { name: "Sanket Pawar", id: "sanketpawar1103" },
  { name: "Nikhil Chodavarapu", id: "nikhilchodavarapu" },
  { name: "Deepak Bahuguna", id: "Deepak-Bahuguna07" },
  { name: "Ajoy Bhunia", id: "ajoybhunia" },
  { name: "Amisha Rawat", id: "AmishaRawat1810" },
  { name: "Khaji Umar", id: "StrawHatCoderz" },
  { name: "Javed", id: "javed-27" },
  { name: "Nitesh", id: "LordofJustice" },
  { name: "Mohanthi", id: "mohanthi4" },
  { name: "Vivek", id: "geekyvivekbytes" },
  { name: "Shivang", id: "Fatyoda3" },
  { name: "Haider", id: "Haider-GitHubRepo" },
  { name: "Adithyan", id: "d-joz" },
  { name: "Sirisha", id: "siridalasari" },
  { name: "Gopi", id: "fake-smiler-115" },
  { name: "Adarsh", id: "Dra-vyn" },
  { name: "Gautham", id: "gauthx" },
  { name: "Haji hussain", id: "hajihussain123" },
  { name: "Som", id: "som3000" },
  { name: "Yash", id: "Foam-Ranther" },
  { name: "Lakshmi Charitha", id: "LakshmiCharitha349" },
  { name: "Pradipta", id: "pradipta1023" },
  { name: "Bhargavi", id: "Bhargavipeddakota" },
  { name: "Lavkush", id: "Lavkushkatiyar" },
  { name: "Himanshu", id: "Jaguar-H" },
  { name: "Vikas yadav", id: "Vikasyadav485" },
  { name: "Sagnik Ghosh", id: "SagnikGhosh001" },
  { name: "Rafiya", id: "Rafiya1207" },
  { name: "Vismaya", id: "Vismayaps2004" },
  { name: "Jeniffer Jojo", id: "jenifferjojo" },
  { name: "Arijit", id: "arijit356" },
  { name: "Aniruddha", id: "Aniruddha1609" },
  { name: "Paulami Dutta", id: "PaulamiDutta23" },
  { name: "Kiranmai", id: "kiranmai-117" },
  { name: "Nandini Dasari", id: "Nandinidasari63" },
  { name: "Oiendrila", id: "OIENDRILA-P" },
  { name: "Ayush", id: "ayush8116-tech" },
  { name: "Priyanshu", id: "PriyanshuA23" },
  { name: "Hem Pradeep", id: "HemPradeepthummala" },
  { name: "Dinesh Kumar", id: "dineshkumar8700" },
  { name: "Khasim", id: "scriptingmaverick" },
  { name: "Dasari Karthik", id: "dasarikarthik-06" },
];
